/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DongTienView;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import model.DongTienModel;
import DongTienController.DongTienControl;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import javax.swing.JOptionPane;
import view.HoKhauView;
import javax.swing.GroupLayout.Alignment;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.TitledBorder;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.UIManager;

/**
 *
 * @author MY PC
 */
public class DongTienHK extends javax.swing.JFrame {

    /**
     * Creates new form DọngTienHK
     */
    private JFrame parentJFrame;
    DefaultTableModel table;
    DongTienControl dtControl;
    ArrayList<DongTienModel> dongtienList = new ArrayList<>();
    String maHk = "";
    
    public DongTienHK(String maHK, JFrame parent) {
    	getContentPane().setBackground(new Color(230, 242, 255));
    	setForeground(new Color(0, 102, 153));
    	setVisible(true);
    	setResizable(false);
    	setTitle("Form thu tiền");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(DongTienHK.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        this.parentJFrame = parent;
        this.setLocationRelativeTo(null);
        table = (DefaultTableModel)jTable.getModel();
        dtControl = new DongTienControl(this);
        this.maHk = maHK;
       dongtienList = dtControl.getKhoanThuTable(maHK);
       setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        this.hienThiBangKhoanThu(dongtienList);
        
        this.dtControl.getThongTinHoKhau(maHK);
        
        try{
            this.dienText.setText(dtControl.getDichVu(maHK,"Điện").getSuDung()+"");  
        }catch(Exception e){
            this.dienText.setText("0_kWh");
        }
        
        try{
            this.nuocText.setText(dtControl.getDichVu(maHK,"Nước").getSuDung()+"");
            
        }catch(Exception e){
            this.nuocText.setText("0_so");
        }
                
        try{
            this.InternetText.setText(dtControl.getDichVu(maHK,"Internet").getSuDung()+"");
            
        }catch(Exception e){
            this.InternetText.setText("no_internet");
        }
        
        try{
            this.oto.setText(dtControl.getPhuongTien(maHK).getOto()+"");
            this.xemay.setText(dtControl.getPhuongTien(maHK).getXemay()+""); 
        }
        catch(Exception e){
            this.oto.setText("0");
            this.xemay.setText("0");
        }
        
        int rowCount = table.getRowCount();
        int total = 0;
        int totalThieu = 0;
        for (int i = 0; i < rowCount; i++) {
            Object value = table.getValueAt(i, 1);
            if (value instanceof Number) {
                total += ((Number) value).intValue();
                String value2 = table.getValueAt(i, 4).toString();
                if(value2.equals("false")){
                    totalThieu += ((Number) value).intValue();
                }
            }
        }
        this.sum.setText(total+"");
        this.thieu.setText(totalThieu+"");
        
    }
    
    public void hienThiBangKhoanThu(ArrayList<DongTienModel> dongtien){
     for(DongTienModel i : dongtien){
         if(dtControl.trangThaiKhoanThu(i.getMaKhoanThu()).getTrangThai().equals("Chưa hoàn thành")){
         String soTienDong = "0";
         boolean trangthai = false;
         if(i.getTrangThai().equals("Đã đóng")){
             soTienDong = i.getSoTien()+"";
             trangthai = true;
         }
        table.addRow(new Object[]{i.getTenKhoanThu(),i.getSoTien(),i.getNgayDong()+"",soTienDong, trangthai});
        }
     }
     
    }
    
    public void hienThiThongTinHoKhau(DongTienModel tt){
        this.soNha.setText(tt .getSoNha());
        this.tenChuHo.setText(tt.getTenChuHo());
        this.dientich.setText(tt.getDienTich()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane1.setBackground(UIManager.getColor("Button.background"));
        jTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        dienText = new javax.swing.JTextField();
        dienText.setBackground(new Color(255, 255, 255));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3.setForeground(new Color(0, 102, 153));
        tenChuHo = new javax.swing.JTextField();
        tenChuHo.setBackground(new Color(255, 255, 255));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel4.setForeground(new Color(0, 102, 153));
        soNha = new javax.swing.JTextField();
        soNha.setBackground(new Color(255, 255, 255));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel5.setForeground(new Color(0, 102, 153));
        oto = new javax.swing.JTextField();
        oto.setBackground(new Color(255, 255, 255));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6.setForeground(new Color(0, 102, 153));
        xemay = new javax.swing.JTextField();
        xemay.setBackground(new Color(255, 255, 255));
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel7.setForeground(new Color(0, 102, 153));
        dientich = new javax.swing.JTextField();
        dientich.setBackground(new Color(255, 255, 255));
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel8.setForeground(new Color(0, 102, 153));
        nuocText = new javax.swing.JTextField();
        nuocText.setBackground(new Color(255, 255, 255));
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel9.setForeground(new Color(0, 102, 153));
        InternetText = new javax.swing.JTextField();
        InternetText.setBackground(new Color(255, 255, 255));
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton1.setBackground(new Color(0, 102, 153));
        jButton1.setForeground(new Color(255, 255, 255));
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton2.setBackground(new Color(0, 102, 153));
        jButton2.setForeground(new Color(255, 255, 255));
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Tahoma", Font.BOLD, 13));
        jLabel10.setForeground(new Color(0, 102, 153));
        sum = new javax.swing.JTextField();
        sum.setBackground(new Color(255, 255, 255));
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Tahoma", Font.BOLD, 13));
        jLabel11.setForeground(new Color(0, 102, 153));
        thieu = new javax.swing.JTextField();
        thieu.setBackground(new Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));
        TitledBorder titledBorder = BorderFactory.createTitledBorder(null, "Thu tiền form", TitledBorder.LEFT, TitledBorder.TOP, null, new Color(0, 102, 204));
        titledBorder.setTitleColor(Color.decode("#0066cc")); // Đổi màu chữ tiêu đề thành màu xanh
        titledBorder.setTitleFont(new Font("Tahoma", Font.BOLD, 18)); // Đổi font chữ của tiêu đề
        titledBorder.setTitlePosition(TitledBorder.TOP); // Đặt vị trí tiêu đề lên trên cùng
        titledBorder.setTitleJustification(TitledBorder.LEADING); // Đặt căn lề tiêu đề ở giữa
        jPanel1.setBorder(null);
     //   jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thu tiền Form"));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên khoản thu", "Số tiền", "Ngày đóng", "Số tiền đóng", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable);

        jLabel2.setText("Số nhà:");

        dienText.setEditable(false);

        jLabel3.setText("Tên chủ hộ");

        tenChuHo.setEditable(false);

        jLabel4.setText("Diện tích");

        soNha.setEditable(false);

        jLabel5.setText("Số ô tô:");

        oto.setEditable(false);
        oto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otoActionPerformed(evt);
            }
        });

        jLabel6.setText("Số xe máy:");

        xemay.setEditable(false);

        jLabel7.setText("Số điện:");

        dientich.setEditable(false);

        jLabel8.setText("Số nước:");

        nuocText.setEditable(false);

        jLabel9.setText("Internet:");

        InternetText.setEditable(false);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setText("Tổng");

        sum.setEditable(false);
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        jLabel11.setText("Còn thiếu:");

        thieu.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(8)
        					.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 41, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(sum, 98, 98, 98)
        					.addPreferredGap(ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
        					.addComponent(jLabel11, GroupLayout.PREFERRED_SIZE, 72, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(thieu, GroupLayout.PREFERRED_SIZE, 83, GroupLayout.PREFERRED_SIZE)
        					.addGap(204)
        					.addComponent(jButton1)
        					.addGap(18)
        					.addComponent(jButton2))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(20)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(soNha, GroupLayout.PREFERRED_SIZE, 140, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 77, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        							.addGap(18)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(dientich)
        								.addComponent(tenChuHo, GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))))
        					.addGap(27)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGap(47)
        									.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        									.addComponent(oto, 76, 76, 76))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGap(27)
        									.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 89, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.UNRELATED)
        									.addComponent(xemay, 76, 76, 76)))
        							.addGap(18)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)
        								.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE)))
        						.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 58, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(dienText)
        						.addComponent(InternetText)
        						.addComponent(nuocText, 113, 113, Short.MAX_VALUE))
        					.addPreferredGap(ComponentPlacement.RELATED, 25, Short.MAX_VALUE))
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel2)
        					.addComponent(soNha, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel5)
        					.addComponent(oto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel7))
        				.addComponent(dienText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(tenChuHo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel6)
        				.addComponent(xemay, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8)
        				.addComponent(nuocText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(dientich, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9)
        				.addComponent(InternetText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton2)
        				.addComponent(jButton1)
        				.addComponent(thieu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel11)
        				.addComponent(sum, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel10))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 746, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 626, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

            int k = 0;
            for(DongTienModel i: dongtienList){
                LocalDate currentDate = LocalDate.now();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String formattedDate = currentDate.format(formatter);
                Date ngayDong;
                
                ngayDong = java.sql.Date.valueOf(formattedDate); 
                boolean trangthai = table.getValueAt(k, 4).toString().equals("true");
                
                if(i.getTrangThai().equals("Chưa đóng") && trangthai){
                    i.setTrangThai("Đã đóng");
                    if(!table.getValueAt(k, 3).equals("")){
                        if(Integer.parseInt(table.getValueAt(k, 1)+"")!=0){
                            i.setSoTien(Integer.parseInt(table.getValueAt(k, 1)+"")); 
                        }else{
                            i.setSoTien(Integer.parseInt(table.getValueAt(k, 3)+""));
                        }
                        i.setNgayDong(ngayDong);
                        dtControl.updatePhiDongGop(i.getMaKhoanThu(), i.getSoTien());
                    }       
                }
                k++;
            }
            this.dtControl.UpdateKhoanThu(dongtienList);
            DongTienHK view = new DongTienHK(maHk, parentJFrame);
            dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            HoKhauView viewMain = (HoKhauView)parentJFrame;
            this.setVisible(false);// TODO add your handling code here:
            viewMain.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void otoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_otoActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed

    }//GEN-LAST:event_sumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InternetText;
    private javax.swing.JTextField dienText;
    private javax.swing.JTextField dientich;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField nuocText;
    private javax.swing.JTextField oto;
    private javax.swing.JTextField soNha;
    private javax.swing.JTextField sum;
    private javax.swing.JTextField tenChuHo;
    private javax.swing.JTextField thieu;
    private javax.swing.JTextField xemay;
}
