/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TaiKhoanView;

import TaiKhoanController.doiMatKhauController;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.TaiKhoanModel;
import view.*;
import java.awt.Toolkit;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;

/**
 *
 * @author MY PC
 */
public class DoiMatKhauView extends javax.swing.JFrame {

    /**
     * Creates new form DoiMatKhauView
     */
    JFrame parent = new JFrame();
    doiMatKhauController dmkControl;
    String vaitro = "";
    private String usernameOld = "";
    public DoiMatKhauView(JFrame parent,String vaitro) {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(DoiMatKhauView.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        
        this.parent = parent;
        this.dmkControl = new doiMatKhauController(this);
        this.dmkControl.thongTinTaiKhoan(vaitro);
        this.role.setEditable(false);
        this.vaitro = vaitro;
        
        this.setTitle("Đổi mật khẩu");
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setVisible(true);
    }
    
    public void hienThiThongTinTaiKhoan(TaiKhoanModel tk){
        this.user.setText(tk.getUsername());
        this.role.setText(tk.getRole());
        this.usernameOld = tk.getUsername();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        user = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(new Color(0, 102, 153));
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        passnew = new javax.swing.JPasswordField();
        passrepeat = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(new Color(0, 102, 153));
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(new Color(0, 102, 153));
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setForeground(new Color(0, 102, 153));
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        role = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));

        jLabel1.setText("Tên đăng nhập: ");

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Đổi thông tin tài khoản");

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Mật khẩu mới:");

        jLabel5.setText("Nhập lại:");

        jLabel6.setText("Vai trò:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(59, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jButton1)
        					.addGap(18)
        					.addComponent(jButton2)
        					.addGap(11))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel3)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(user, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(passnew, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(passrepeat, GroupLayout.PREFERRED_SIZE, 112, GroupLayout.PREFERRED_SIZE)))
        					.addGap(105))))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(14)
        			.addComponent(jLabel6)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(role, GroupLayout.PREFERRED_SIZE, 63, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        				.addComponent(role, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel3)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel1)
        				.addComponent(user, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(23)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(passnew, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(25)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel5)
        				.addComponent(passrepeat, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        TaiKhoanModel taikhoan = new TaiKhoanModel();
        
        if(String.valueOf(this.passnew.getPassword()).equals("")|| String.valueOf(this.passrepeat.getPassword()).equals("")|| this.user.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin !");
        }else{
            if(String.valueOf(this.passnew.getPassword()).equals(String.valueOf(this.passrepeat.getPassword()))){
            taikhoan.setUsername(this.user.getText());
            taikhoan.setPassword(String.valueOf(this.passrepeat.getPassword())); 
            taikhoan.setRole(vaitro);
            dmkControl.updateTaiKhoan(taikhoan, usernameOld);
            }else{
            JOptionPane.showMessageDialog(this, "Mật khẩu không trùng khớp");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           MainView main = (MainView)parent;
           this.setVisible(false);
           main.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField passnew;
    private javax.swing.JPasswordField passrepeat;
    private javax.swing.JTextField role;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables
}
