/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import TaiKhoanView.DoiMatKhauView;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import TaiKhoanView.DoiMatKhauView;
import controller.MainViewController;
import javax.swing.GroupLayout.Alignment;
import javax.swing.ImageIcon;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;

import javax.swing.JLabel;
import javax.swing.JTextArea;
import java.awt.Toolkit;
import javax.swing.SwingConstants;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author MY PC
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    MainViewController mainControl;
    public MainView(String role) {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(MainView.class.getResource("/img/apartment_13889041-min.png")));
    	getContentPane().setBackground(new Color(230, 242, 255));
        initComponents();
        this.setTitle("Phần mềm quản lý chung cư v2.2");
        this.setLocationRelativeTo(null);
        LoginView.vaiTroQuanLy = role;
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.mainControl = new MainViewController(this);
        
        this.mainControl.thongTinChungCu();
        
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                if (JOptionPane.showConfirmDialog(null, "Are you sure to close??", "Warning!!", JOptionPane.YES_NO_OPTION) == 0) {
                    dispose();
                    System.exit(0);
                }
            }
            
        });
        this.setVisible(true);
    }
    
    public void hienThiThongTinChungCu(int hokhau, int nhankhau, int tamtru, int tamvang, int phuongtien){
        this.hokhauText.setText(hokhau+"");
        this.nhankhauText.setText(nhankhau+"");
        this.phuongtienText.setText(phuongtien+"");
        this.tamtruText.setText(tamtru+"");
        this.tamvangText.setText(tamvang+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel3.setForeground(new Color(0, 102, 153));
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton6.setBorderPainted(false);
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel1.setIcon(new ImageIcon(MainView.class.getResource("/img/users.png")));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel2.setIcon(new ImageIcon(MainView.class.getResource("/img/village.png")));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel3.setIcon(new ImageIcon(MainView.class.getResource("/img/verified-user.png")));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(new Color(0, 102, 153));
        jLabel4.setIcon(new ImageIcon(MainView.class.getResource("/img/cancel.png")));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(new Color(0, 102, 153));
        jLabel5.setIcon(new ImageIcon(MainView.class.getResource("/img/sedan.png")));
        phuongtienText = new javax.swing.JTextField();
        tamtruText = new javax.swing.JTextField();
        tamvangText = new javax.swing.JTextField();
        nhankhauText = new javax.swing.JTextField();
        hokhauText = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        	}
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new Color(255, 255, 255));

        jButton5.setText("Đăng xuất");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Đổi mật khẩu");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(102, 204, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Số nhân khẩu:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Số hộ khẩu:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tạm trú:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Tạm vắng:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Phương tiện:");

        phuongtienText.setEditable(false);

        tamtruText.setEditable(false);

        tamvangText.setEditable(false);

        nhankhauText.setEditable(false);

        hokhauText.setEditable(false);

        jButton7.setText("Thêm tài khoản");
        
        lblNewLabel_1 = new JLabel("Quản lí chung cư");
        lblNewLabel_1.setBackground(new Color(0, 102, 153));
        lblNewLabel_1.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel_1.setFont(new Font("Segoe UI Light", Font.BOLD | Font.ITALIC, 25));
        
        lblNewLabel_2 = new JLabel("BLUEMOON");
        lblNewLabel_2.setBackground(new Color(0, 102, 153));
        lblNewLabel_2.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel_2.setFont(new Font("SimSun", Font.BOLD, 28));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addGap(77))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED))
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(phuongtienText)
        				.addComponent(nhankhauText)
        				.addComponent(hokhauText, GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
        				.addComponent(tamtruText)
        				.addComponent(tamvangText))
        			.addGap(445))
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(176)
        			.addComponent(jButton7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton6)
        			.addPreferredGap(ComponentPlacement.RELATED, 339, Short.MAX_VALUE)
        			.addComponent(jButton5)
        			.addContainerGap())
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblNewLabel_1, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblNewLabel_2, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(397, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addComponent(lblNewLabel_1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblNewLabel_2)
        			.addGap(86)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(hokhauText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(nhankhauText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(tamtruText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel3))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(tamvangText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(18)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(phuongtienText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addPreferredGap(ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton5)
        				.addComponent(jButton6)
        				.addComponent(jButton7))
        			.addGap(13))
        );
        jPanel3.setLayout(jPanel3Layout);
        
        panel = new JPanel();
        panel.setBackground(new Color(230, 242, 255));
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton2.setHorizontalAlignment(SwingConstants.LEFT);
        jButton2.setIcon(new ImageIcon(MainView.class.getResource("/img/house.png")));
        jButton2.setFont(new Font("Segoe UI Variable", Font.BOLD, 14));
        jButton2.setFocusable(false);
        
                jButton2.setText("Hộ khẩu");
                jButton2.setName(""); // NOI18N
                jButton2.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton2ActionPerformed(evt);
                    }
                });
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton1.setHorizontalAlignment(SwingConstants.LEFT);
        jButton1.setIcon(new ImageIcon(MainView.class.getResource("/img/business-profile.png")));
        jButton1.setFont(new Font("Segoe UI Variable", Font.BOLD, 14));
        
                jButton1.setText("Nhân khẩu");
                jButton1.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton1ActionPerformed(evt);
                    }
                });
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        jButton4.setHorizontalAlignment(SwingConstants.LEFT);
        jButton4.setIcon(new ImageIcon(MainView.class.getResource("/img/money-bags.png")));
        jButton4.setFont(new Font("Segoe UI Variable", Font.BOLD, 14));
        
                jButton4.setText("Khoản thu");
                jButton4.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton4ActionPerformed(evt);
                    }
                });
        jButton3 = new javax.swing.JButton();
        jButton3.setBorderPainted(false);
        jButton3.setHorizontalAlignment(SwingConstants.LEFT);
        jButton3.setIcon(new ImageIcon(MainView.class.getResource("/img/sedan.png")));
        jButton3.setFont(new Font("Segoe UI Variable", Font.BOLD, 14));
        
                jButton3.setText("Gửi xe");
                jButton3.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jButton3ActionPerformed(evt);
                    }
                });
        
               
                
        
                
                
        
                
  
        
        // Load the image from the resource path
        ImageIcon originalIcon = new ImageIcon(getClass().getResource("/img/project-manager.png"));

        // Resize the image to fit within the JLabel's fixed size
        Image image = originalIcon.getImage();
        Image resizedImage = image.getScaledInstance(100, 100, Image.SCALE_SMOOTH);
        ImageIcon resizedIcon = new ImageIcon(resizedImage);

        // Create a JLabel and set the ImageIcon as its icon
        JLabel lblNewLabel = new JLabel(resizedIcon);
        
        
        
        
        
        
        
        GroupLayout gl_panel = new GroupLayout(panel);
        gl_panel.setHorizontalGroup(
        	gl_panel.createParallelGroup(Alignment.TRAILING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addGroup(gl_panel.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
        				.addGroup(gl_panel.createParallelGroup(Alignment.TRAILING)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
        					.addGroup(gl_panel.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
        						.addGroup(gl_panel.createSequentialGroup()
        							.addContainerGap()
        							.addComponent(lblNewLabel, GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
        						.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap())
        );
        gl_panel.setVerticalGroup(
        	gl_panel.createParallelGroup(Alignment.LEADING)
        		.addGroup(gl_panel.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblNewLabel)
        			.addGap(77)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(194, Short.MAX_VALUE))
        );
        panel.setLayout(gl_panel);
        GroupLayout groupLayout = new GroupLayout(getContentPane());
        groupLayout.setHorizontalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(10)
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 417, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        groupLayout.setVerticalGroup(
        	groupLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(groupLayout.createSequentialGroup()
        			.addGap(11)
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 445, GroupLayout.PREFERRED_SIZE))
        		.addComponent(jPanel3, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 456, GroupLayout.PREFERRED_SIZE)
        );
        getContentPane().setLayout(groupLayout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        GuiXeView viewGX = new GuiXeView();
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        KhoanThuView viewKT = new KhoanThuView();
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HoKhauView viewHK = new HoKhauView();
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NhanKhauView viewNK = new NhanKhauView();
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        dispose();
        LoginView login = new LoginView();
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DoiMatKhauView mkView = new DoiMatKhauView(this,LoginView.vaiTroQuanLy);
        this.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed
    private javax.swing.JTextField hokhauText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nhankhauText;
    private javax.swing.JTextField phuongtienText;
    private javax.swing.JTextField tamtruText;
    private javax.swing.JTextField tamvangText;
    private JPanel panel;
    private JLabel lblNewLabel_1;
    private JLabel lblNewLabel_2;
}
