/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HoKhauView;

import HoKhauController.HoKhauFormController;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import DongTienView.DongTienHK;
import model.HoKhauModel;
import model.NhanKhauModel;
import model.ThanhVienModel;
import view.HoKhauView;
import view.NhanKhauView;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author MY PC
 */
public class HoKhauForm extends javax.swing.JFrame {

    /**
     * Creates new form HoKhauForm
     */
    String option = new String();
    HoKhauFormController hk;
    DefaultTableModel table;
    private String maHK = "";
    private JFrame parentJframe;
    
    public HoKhauForm(String option, String maHK, JFrame parenJFrame) {
    	setTitle("Thông tin hộ khẩu");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(HoKhauForm.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        this.parentJframe = parenJFrame;
        this.option = option;
        this.maHK = maHK;
        
        table = (DefaultTableModel)jTable1.getModel();
        this.setLocationRelativeTo(null);
        hk = new HoKhauFormController(this);
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
        
        
        if(option.equals("xem")){
            this.jButton1.setVisible(false);
            this.jButton4.setVisible(false);
            this.soNhaText.setEditable(false);
            this.loaisoBox.setVisible(true);
            this.chuyendi.setVisible(true);
            
        }else if(option.equals("edit")){
            this.jButton1.setVisible(true);
            this.jButton4.setVisible(true);   
            this.loaisoBox.setVisible(true);
            this.chuyendi.setVisible(false);
        }
        
        this.hk.getHoKhau(maHK);
        this.hk.getThanhVien(maHK);
    }
    
    public void hienThiHoKhau(HoKhauModel hk){
        
        this.soNhaText.setText(hk.getSoNha());
        this.loaisoBox.setSelectedItem(hk.getLoaiSo());
        this.DienTich.setText(hk.getDienTich()+"");
        
        this.hk.getChuHo(hk.getId_chu());
        
    }
    
    public void hienThiChuHo(NhanKhauModel nk){
        this.CCCDText.setText(nk.getCCCD());
        this.dateText.setText(nk.getNamSinh()+"");
        this.nameText.setText(nk.getHoTen());
    }
    
    public void hienThiThanhVien(ArrayList<ThanhVienModel>list){
      for(ThanhVienModel i : list){
        table.addRow(new Object[]{i.getIdNhanKhau(),i.getHoTen(), i.getQuanHeVoiChuHo()});
      }
    }
    
    /*public void hienThiNhanKhau(NhanKhauModel nk){
        if(option.equals("chuho")){

            if(this.kiemTraThanhVien(nk.getCCCD())){
                this.nameText.setText(nk.getHoTen());
                this.CCCDText.setText(nk.getCCCD());
                this.dateText.setText(nk.getNamSinh()+"");
                this.idHText.setText(nk.getID()+"");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Đã chọn "+nk.getHoTen()+"\nVui lòng chọn lại !");
            }            
        }else if(option.equals("thanhvien")){
            if(this.kiemTraThanhVien(nk.getCCCD()))
                table.addRow(new Object[]{nk.getCCCD(),nk.getHoTen(),""});
            else{
                JOptionPane.showMessageDialog(rootPane, "Đã chọn "+nk.getHoTen()+"\nVui lòng chọn lại !");
            }
        }
        
    }*/
    
    /*public boolean kiemTraThanhVien(String CCCD){
        int rowCount = table.getRowCount();
        for (int row = 0; row < rowCount; row++) {
            Object value = table.getValueAt(row, 0);
            if(value.equals(CCCD)){
                return false;
            }
        }
        if(this.CCCDText.getText().equals(CCCD)){
            return false;
        }
        return true;
    }*/
    
    /*public void chonNhanKhau(String CCCD){
        this.hk.getNhanKhau(CCCD);
    }*/
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(0, 102, 153));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setForeground(new Color(0, 102, 153));
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setForeground(new Color(0, 102, 153));
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 13));
        soNhaText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        CCCDText = new javax.swing.JTextField();
        dateText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        loaisoBox = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jPanel3.setBackground(new Color(230, 242, 255));
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setForeground(new Color(0, 102, 153));
        jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 13));
        DienTich = new javax.swing.JTextField();
        chuyendi = new javax.swing.JButton();
        chuyendi.setBorderPainted(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));

        jLabel1.setText("Số nhà:");

        jLabel2.setText("Loại sổ:");

        jLabel3.setText("Chủ hộ:");

        jLabel4.setText("CCCD chủ hộ:");

        jLabel5.setText("Ngày sinh chủ hộ:");

        soNhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soNhaTextActionPerformed(evt);
            }
        });

        nameText.setEditable(false);
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        CCCDText.setEditable(false);
        CCCDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCCDTextActionPerformed(evt);
            }
        });

        dateText.setEditable(false);
        dateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateTextActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        loaisoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường trú", "Tạm trú" }));

        jPanel3.setBorder(null); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Họ và tên", "Quan hệ với chủ hộ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        
        JLabel lblThnhVin = new JLabel();
        lblThnhVin.setText("Thành viên");
        lblThnhVin.setForeground(new Color(0, 102, 153));
        lblThnhVin.setFont(new Font("Segoe UI Variable", Font.BOLD, 15));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        				.addComponent(lblThnhVin, GroupLayout.PREFERRED_SIZE, 102, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel3Layout.createSequentialGroup()
        			.addComponent(lblThnhVin, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel3.setLayout(jPanel3Layout);

        jLabel7.setText("Diện Tích: ");

        DienTich.setEditable(false);
        DienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DienTichActionPerformed(evt);
            }
        });

        chuyendi.setText("Chuyển đi nơi khác");
        chuyendi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyendiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap()
        					.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(25)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel4, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel5, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 95, GroupLayout.PREFERRED_SIZE))
        					.addGap(109)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(dateText, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(CCCDText, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(soNhaText, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(chuyendi))
        								.addComponent(loaisoBox, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(nameText, GroupLayout.PREFERRED_SIZE, 231, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE)
        											.addGap(18)
        											.addComponent(jButton4)
        											.addGap(18)
        											.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 73, GroupLayout.PREFERRED_SIZE))
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addComponent(jLabel7)
        											.addGap(18)
        											.addComponent(DienTich, GroupLayout.PREFERRED_SIZE, 110, GroupLayout.PREFERRED_SIZE)))))
        							.addGap(31, 31, Short.MAX_VALUE)))))
        			.addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(43)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(soNhaText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(chuyendi)
        				.addComponent(jLabel1))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(loaisoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(nameText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7)
        				.addComponent(DienTich, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(CCCDText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel5)
        					.addComponent(dateText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(41)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton4)
        						.addComponent(jButton2))))
        			.addGap(20)
        			.addComponent(jPanel3, GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void soNhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soNhaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_soNhaTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void CCCDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCCDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCCDTextActionPerformed

    private void dateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateTextActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        HoKhauView viewMain = new HoKhauView ();
        this.setVisible(false);
        viewMain.setLocationRelativeTo(null);
        viewMain.setVisible(true);
 // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void DienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DienTichActionPerformed

    private void chuyendiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyendiActionPerformed
            int response = JOptionPane.showConfirmDialog(this, "Gia đình bạn chắc chắn muốn chuyển đi nơi khác ?", "Chuyển đi nơi khác", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    hk.chuyenDiNoiKhac(this.maHK);
                }          
    }//GEN-LAST:event_chuyendiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCCDText;
    private javax.swing.JTextField DienTich;
    private javax.swing.JButton chuyendi;
    private javax.swing.JTextField dateText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> loaisoBox;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField soNhaText;
}
