/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HoKhauView;

import TamTruTamVangController.khaiBaoController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.TamTruTamVangModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.UIManager;

import java.awt.Font;
import java.awt.Color;
import java.awt.Toolkit;

/**
 *
 * @author MY PC
 */
public class KhaiBaoTinhTrangView extends javax.swing.JFrame {

    /**
     * Creates new form KhaiBaoTinhTrangView
     */
    khaiBaoController kbControl;
    String option = "";
    String CCCD ="";
    String tinhTrangDK= "";
    public KhaiBaoTinhTrangView(String option, String CCCD, String tinhTrangDK) {
    	setIconImage(Toolkit.getDefaultToolkit().getImage(KhaiBaoTinhTrangView.class.getResource("/img/apartment_13889041-min.png")));
    	setTitle("Khai Báo Tình Trạng");
        initComponents();
        this.setLocationRelativeTo(null);
        
        kbControl = new khaiBaoController(this);
        
        this.option = option;
        this.CCCD = CCCD;
        this.tinhTrangDK = tinhTrangDK;
        
        if(option.equals("add")){
            this.cheDoThem();
        }else if(option.equals("xem")){
            this.chonKhaiBao(CCCD);
            this.cheDoXem();
        }
        
         setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setVisible(true);
    }
        
    public void chonKhaiBao(String CCCD){
        this.kbControl.xemKhaiBao(CCCD,tinhTrangDK);
    }
    public void hienThiThongTinKhaiBao(TamTruTamVangModel khaibao, String soNha){
        this.CCCDText.setText(khaibao.getCCCD());
        this.diaDiemText.setText("");
        this.hoTenText.setText("");
        this.chuHoText.setText("");
        this.ngayBDText.setDate(khaibao.getBatDau());
        this.ngayKTText.setDate(khaibao.getKetThuc());
        
        this.loaiBox.setSelectedItem(khaibao.getLoaiDangKy()); 
        
        this.chuyenDenText.setText(khaibao.getDiaDiem());
        this.lidoText.setText(khaibao.getLido());
        this.diaDiemText.setText(soNha);
        if(!(kbControl.getNhanKhau(CCCD)== null)){
            this.hoTenText.setText(kbControl.getNhanKhau(CCCD).getHoTen());
        }else{
            JOptionPane.showMessageDialog(this, "Không tồn tại mã CCCD này !");
        }
        
        if(!(kbControl.getHoKhau(soNha)==null)){
            this.chuHoText.setText(kbControl.getHoKhau(soNha).getTenChu());
        }else{
            JOptionPane.showMessageDialog(this, "Không tồn tại số nhà này !");
        }
}
    
    public void xoaForm(){
        this.CCCDText.setText("");
        this.ngayBDText.cleanup();
        this.ngayKTText.cleanup();
        this.lidoText.setText("");
        this.diaDiemText.setText("");
        this.hoTenText.setText("");
    }
    
    public void cheDoXem(){
        this.CCCDText.setEditable(false);
        this.diaDiemText.setEditable(false);
        this.hoTenText.setEditable(false);
        this.chuHoText.setEditable(false);
        this.ngayBDText.setEnabled(false);
        this.ngayKTText.setEnabled(false);
        this.loaiBox.setEnabled(false);
        this.chuyenDenText.setEditable(false);
        this.lidoText.setEditable(false);
        this.jButton1.setVisible(false);
        this.jButton4.setVisible(false);
        this.jButton3.setVisible(true);
        this.jButton5.setVisible(false);
        this.loaiBox.setEnabled(false);
    }
    
    public void cheDoThem(){
        this.CCCDText.setEditable(true);
        this.diaDiemText.setEditable(false);
        this.hoTenText.setEditable(false);
        this.chuHoText.setEditable(false);
        this.ngayBDText.setEnabled(true);
        this.ngayKTText.setEnabled(true);
        this.loaiBox.setEnabled(true);
        this.chuyenDenText.setEditable(false);
        this.lidoText.setEditable(true);
        this.jButton1.setVisible(true);
        this.jButton4.setVisible(true);
        this.jButton3.setVisible(false);
        this.jButton5.setVisible(true);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(230, 242, 255));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6.setForeground(new Color(0, 102, 153));
        CCCDText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        loaiBox = new javax.swing.JComboBox<>();
        hoTenText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel7.setForeground(new Color(0, 102, 153));
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel8.setForeground(new Color(0, 102, 153));
        lidoText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton3.setBorderPainted(false);
        jButton5 = new javax.swing.JButton();
        jButton5.setBorderPainted(false);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel9.setForeground(new Color(0, 102, 153));
        diaDiemText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel10.setForeground(new Color(0, 102, 153));
        chuHoText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel11.setForeground(new Color(0, 102, 153));
        chuyenDenText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        
        
        ngayBDText = new com.toedter.calendar.JDateChooser();
        ngayBDText.setBackground(Color.WHITE);
        ngayBDText.getCalendarButton().setBorderPainted(true);
        ngayBDText.getCalendarButton().setBackground(Color.white);;
        ngayKTText = new com.toedter.calendar.JDateChooser();
        ngayKTText.getCalendarButton().setBorderPainted(true);
        ngayKTText.getCalendarButton().setBackground(Color.white);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));
        jPanel1.setBorder(null); // NOI18N

        jLabel1.setText("CCCD:");

        jLabel2.setText("Họ tên:");

        jLabel3.setText("Ngày bắt đầu:");

        jLabel6.setText("Loại khai báo:");

        CCCDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCCDTextActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        loaiBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tạm trú", "Tạm vắng", "tạm vắng" }));

        hoTenText.setEditable(false);
        hoTenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoTenTextActionPerformed(evt);
            }
        });

        jLabel7.setText("Ngày kết thúc:");

        jLabel8.setText("Số nhà:");

        lidoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lidoTextActionPerformed(evt);
            }
        });

        jButton3.setText("Hoàn thành");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setText("Check");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel9.setText("Lí do:");

        diaDiemText.setEditable(false);

        jLabel10.setText("Chủ hộ:");

        chuHoText.setEditable(false);

        jLabel11.setText("Chuyển đến:");

        chuyenDenText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuyenDenTextActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("(*)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("(*)");

        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("(*)");

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));
        jLabel13.setText("(*)");

        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("(*)");

        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("(*)");

        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("(*)");
        
        lblThngTinKhai = new JLabel();
        lblThngTinKhai.setForeground(new Color(0, 102, 153));
        lblThngTinKhai.setFont(new Font("Segoe UI Variable", Font.BOLD, 15));
        lblThngTinKhai.setText("Thông tin khai báo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jButton3)
        					.addPreferredGap(ComponentPlacement.RELATED, 304, Short.MAX_VALUE)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton4)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        					.addGap(27))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel7, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel9, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addGap(83))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        							.addPreferredGap(ComponentPlacement.RELATED)))
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(lidoText)
        							.addComponent(loaiBox, 0, 176, Short.MAX_VALUE)
        							.addComponent(hoTenText)
        							.addComponent(ngayBDText, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(ngayKTText, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(CCCDText, 176, 176, 176))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel4)
        								.addComponent(jLabel5))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGap(26)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        										.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE)
        										.addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 49, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(chuHoText, 123, 123, 123)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addComponent(diaDiemText, GroupLayout.PREFERRED_SIZE, 105, GroupLayout.PREFERRED_SIZE)
        											.addPreferredGap(ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
        											.addComponent(jLabel16)))
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addPreferredGap(ComponentPlacement.UNRELATED)
        											.addComponent(jButton5))
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addGap(3)
        											.addComponent(jLabel17)))
        									.addGap(2))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel11)
        									.addGap(18)
        									.addComponent(chuyenDenText, 185, 185, 185)
        									.addContainerGap())))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel12)
        								.addComponent(jLabel13)
        								.addComponent(jLabel14))
        							.addGap(0, 313, Short.MAX_VALUE))))))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(218)
        			.addComponent(lblThngTinKhai, GroupLayout.PREFERRED_SIZE, 172, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(296, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(6)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(lblThngTinKhai)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel8)
        						.addComponent(diaDiemText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton5)
        						.addComponent(jLabel4)
        						.addComponent(jLabel16)))
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel1)
        					.addComponent(CCCDText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(hoTenText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel10)
        				.addComponent(chuHoText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5)
        				.addComponent(jLabel17)
        				.addComponent(jLabel2))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3)
        					.addComponent(jLabel12))
        				.addComponent(ngayBDText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(ngayKTText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel7)
        					.addComponent(jLabel13)))
        			.addPreferredGap(ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(loaiBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel14))
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(lidoText, GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        						.addComponent(jLabel9)
        						.addComponent(chuyenDenText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        								.addComponent(jButton2)
        								.addComponent(jButton4)
        								.addComponent(jButton1))
        							.addGap(17))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jButton3)
        							.addContainerGap())))
        				.addComponent(jLabel11)))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CCCDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCCDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCCDTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
     Date batDau = new Date();
     Date ketThuc = new Date();
    try{
        String ngay = dateFormat.format(this.ngayBDText.getDate());
        String ngay2 = dateFormat.format(this.ngayKTText.getDate());
        batDau = dateFormat.parse(ngay);
        ketThuc = dateFormat.parse(ngay2);
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Sai định dạng ngày");  
        return;
    }
        
        
        
        TamTruTamVangModel kb = new TamTruTamVangModel();

        String CCCD = new String();
        //String hoTen = new String();
        String hoTen = new String();
        String loaiDangKi = new String ();
        String diaDiem = new String();
        String lido = new String();

        if(this.CCCDText.getText().equals("")
                || this.hoTenText.getText().equals("")
                || this.chuHoText.getText().equals("")
                || this.diaDiemText.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin !");
        }else{
            try{
                CCCD = this.CCCDText.getText();
                loaiDangKi = this.loaiBox.getSelectedItem()+"";
                lido = this.lidoText.getText();
                if(loaiDangKi.equals("Tạm trú")){
                    diaDiem = diaDiemText.getText();
                }else{
                    diaDiem = this.chuyenDenText.getText();
                }
                hoTen = this.hoTenText.getText();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Vui lòng điền đúng định dạng !");
                return;
            }

            kb.setCCCD(CCCD);
            kb.setBatDau(batDau);
            kb.setKetThuc(ketThuc);
            kb.setLoaiDangKy(loaiDangKi);
            kb.setLido(lido);
            kb.setDiaDiem(diaDiem);
            kb.setName(hoTen);

            //if(option.equals("add")){
                kbControl.addKhaiBao(kb);
            //}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        QuanLiTinhTrangView viewMain = new QuanLiTinhTrangView();
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        xoaForm();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hoTenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoTenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hoTenTextActionPerformed

    private void lidoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lidoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lidoTextActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String CCCD = this.CCCDText.getText();
        String soNha = "";
        try{
        soNha = kbControl.getKiemTraThanhVien(CCCD).getIdHoKhau();
        if(!(kbControl.getNhanKhau(CCCD)== null)){
            this.hoTenText.setText(kbControl.getNhanKhau(CCCD).getHoTen());
        }else{
            JOptionPane.showMessageDialog(this, "Không tồn tại mã CCCD này !");
        }}
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Nhập căn cước công dân !");
        }
        
        
        if(!(kbControl.getHoKhau(soNha)==null)){
            this.chuHoText.setText(kbControl.getHoKhau(soNha).getTenChu());
            this.diaDiemText.setText(soNha);
            if(kbControl.getNhanKhau(CCCD).getTinhTrang().equals("Chưa khai báo")){
                    this.loaiBox.setSelectedItem("Tạm trú");
                    this.loaiBox.setEnabled(false);                   

            }else if(kbControl.getNhanKhau(CCCD).getTinhTrang().equals("Thường trú")){
                this.loaiBox.setSelectedItem("Tạm vắng");
                this.loaiBox.setEnabled(false);
            }else if (kbControl.getNhanKhau(CCCD).getTinhTrang().equals("Tạm trú")){
                if(kbControl.getHoKhau(soNha).getLoaiSo().equals("Thường trú")){
                    this.loaiBox.setSelectedItem("tạm vắng");
                    this.loaiBox.setEnabled(false);
                }else{
                    this.loaiBox.setSelectedItem("Tạm vắng");
                    this.loaiBox.setEnabled(false);                    
                }
                
            }
        }else{
            JOptionPane.showMessageDialog(this, "Không tồn tại số nhà này !");
        }
        
        if(loaiBox.getSelectedItem().equals("Tạm vắng") || loaiBox.getSelectedItem().equals("tạm vắng")){
            chuyenDenText.setEditable(true);
        }else{
            chuyenDenText.setEditable(false);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void chuyenDenTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuyenDenTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuyenDenTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String opt = "";
        kbControl.hoanThanh(CCCD,opt);
        QuanLiTinhTrangView viewMain = new QuanLiTinhTrangView();
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCCDText;
    private javax.swing.JTextField chuHoText;
    private javax.swing.JTextField chuyenDenText;
    private javax.swing.JTextField diaDiemText;
    private javax.swing.JTextField hoTenText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lidoText;
    private javax.swing.JComboBox<String> loaiBox;
    private com.toedter.calendar.JDateChooser ngayBDText;
    private com.toedter.calendar.JDateChooser ngayKTText;
    private JLabel lblThngTinKhai;
    // End of variables declaration//GEN-END:variables
}
