/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HoKhauView;

import HoKhauController.taoMoiHoKhauController;
import NhanKhauController.themNhanKhauController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JFrame;
import view.HoKhauView;
import java.util.Date;
import javax.swing.JOptionPane;
import model.HoKhauModel;
import model.NhanKhauModel;
import model.ThanhVienModel;
import service.NhanKhauService;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.border.LineBorder;
import javax.swing.JLabel;


/**
 *
 * @author MY PC
 */
public class taoMoiHoKhau extends javax.swing.JFrame {

    /**
     * Creates new form taoMoiHoKhau
     */
    private JFrame parentJFrame;
    private taoMoiHoKhauController newHKControl;
    
    public taoMoiHoKhau(JFrame parentJframe) {
    	setTitle("Tạo mới hộ khẩu");
    	getContentPane().setBackground(new Color(230, 242, 255));
    	getContentPane().setForeground(new Color(230, 242, 255));
    	setIconImage(Toolkit.getDefaultToolkit().getImage(taoMoiHoKhau.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        this.parentJFrame = parentJframe;
        newHKControl = new taoMoiHoKhauController(this);
        
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.setVisible(true);
    }
    
    public void xoaForm(){
        this.CCCDHKText.setText("");
        this.cccdText.setText("");
        this.DateHKText.setText("");
        this.ngaySinhText.cleanup();
        this.nameHKText.setText("");
        this.nameText.setText("");
        this.jobText.setText("");
        this.countryText.setText("");
        this.workText.setText("");
        this.SoNhaHKText.setText("");
        this.regionText.setText("");
        this.queText.setText("");
        this.DienTich.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(0, 102, 153));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel4.setForeground(new Color(0, 102, 153));
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel5.setForeground(new Color(0, 102, 153));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6.setForeground(new Color(0, 102, 153));
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel7.setForeground(new Color(0, 102, 153));
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel8.setForeground(new Color(0, 102, 153));
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel9.setForeground(new Color(0, 102, 153));
        nameText = new javax.swing.JTextField();
        cccdText = new javax.swing.JTextField();
        regionText = new javax.swing.JTextField();
        countryText = new javax.swing.JTextField();
        workText = new javax.swing.JTextField();
        jobText = new javax.swing.JTextField();
        queText = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton3.setBorderPainted(false);
        sexBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        
        
        
        
        ngaySinhText = new com.toedter.calendar.JDateChooser();
        ngaySinhText.getCalendarButton().setIgnoreRepaint(true);
        ngaySinhText.getCalendarButton().setBackground(Color.white);
        
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel13.setForeground(new Color(0, 102, 153));
        SoNhaHKText = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel14.setForeground(new Color(0, 102, 153));
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel15.setForeground(new Color(0, 102, 153));
        nameHKText = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel16.setForeground(new Color(0, 102, 153));
        CCCDHKText = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel17.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel17.setForeground(new Color(0, 102, 153));
        DateHKText = new javax.swing.JTextField();
        loaisoBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel10.setForeground(new Color(0, 102, 153));
        DienTich = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));
        jPanel1.setBorder(new LineBorder(new Color(51, 153, 204), 1, true)); // NOI18N

        jLabel1.setText("Họ và tên: ");

        jLabel2.setText("CCCD:");

        jLabel3.setText("Ngày sinh: ");

        jLabel4.setText("Giới tính:");

        jLabel5.setText("Dân tộc:");

        jLabel6.setText("Quốc tịch:");

        jLabel7.setText("Nơi làm việc");

        jLabel8.setText("Nghề nghiệp");

        jLabel9.setText("Quê quán:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        cccdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cccdTextActionPerformed(evt);
            }
        });

        regionText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regionTextActionPerformed(evt);
            }
        });

        countryText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextActionPerformed(evt);
            }
        });

        workText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workTextActionPerformed(evt);
            }
        });

        jobText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jobTextActionPerformed(evt);
            }
        });

        queText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                queTextActionPerformed(evt);
            }
        });

        jButton3.setText("Next");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        sexBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));

        jLabel11.setForeground(new java.awt.Color(255, 0, 51));
        jLabel11.setText("(*)");

        jLabel12.setForeground(new java.awt.Color(255, 0, 51));
        jLabel12.setText("(*)");

        jLabel18.setForeground(new java.awt.Color(255, 0, 51));
        jLabel18.setText("(*)");

        jLabel19.setForeground(new java.awt.Color(255, 0, 51));
        jLabel19.setText("(*)");

        jLabel20.setForeground(new java.awt.Color(255, 0, 51));
        jLabel20.setText("(*)");

        jLabel21.setForeground(new java.awt.Color(255, 0, 51));
        jLabel21.setText("(*)");

        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setText("(*)");

        jLabel23.setForeground(new java.awt.Color(255, 0, 51));
        jLabel23.setText("(*)");

        jLabel24.setForeground(new java.awt.Color(255, 0, 51));
        jLabel24.setText("(*)");

        ngaySinhText.setDateFormatString("yyyy-MM-dd");
        
        lblThngTinCh = new JLabel();
        lblThngTinCh.setText("Thông tin chủ hộ");
        lblThngTinCh.setForeground(new Color(0, 102, 153));
        lblThngTinCh.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(lblThngTinCh, GroupLayout.PREFERRED_SIZE, 165, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabel7, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE))
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(countryText, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jLabel19))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(workText, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addComponent(jLabel20))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        										.addComponent(ngaySinhText, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        										.addComponent(cccdText, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE))
        									.addPreferredGap(ComponentPlacement.RELATED)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addComponent(jLabel12)
        										.addComponent(jLabel18, Alignment.TRAILING))))
        							.addGap(40)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel9, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(queText, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(regionText, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE)
        									.addGap(18)
        									.addComponent(sexBox, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel8)
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addGap(129)
        											.addComponent(jButton3))
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addGap(18)
        											.addComponent(jobText, GroupLayout.PREFERRED_SIZE, 168, GroupLayout.PREFERRED_SIZE)))))
        							.addPreferredGap(ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel21, Alignment.TRAILING)
        								.addComponent(jLabel22, Alignment.TRAILING)
        								.addComponent(jLabel23, Alignment.TRAILING)
        								.addComponent(jLabel24, Alignment.TRAILING)))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(nameText, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(jLabel11)
        							.addGap(0, 325, Short.MAX_VALUE)))))
        			.addGap(25))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblThngTinCh, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(nameText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel11))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(cccdText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4)
        				.addComponent(sexBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12)
        				.addComponent(jLabel21))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3)
        					.addComponent(jLabel9)
        					.addComponent(queText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel18)
        					.addComponent(jLabel22))
        				.addComponent(ngaySinhText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(countryText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5)
        				.addComponent(jLabel19)
        				.addComponent(jLabel23)
        				.addComponent(regionText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel7)
        				.addComponent(workText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel8)
        				.addComponent(jLabel20)
        				.addComponent(jLabel24)
        				.addComponent(jobText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addComponent(jButton3)
        			.addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new Color(230, 242, 255));
        jPanel2.setBorder(new LineBorder(new Color(51, 153, 204), 1, true)); // NOI18N

        jLabel13.setText("Số nhà:");

        jLabel14.setText("Loại số:");

        jLabel15.setText("Tên chủ hộ:");

        nameHKText.setEditable(false);

        jLabel16.setText("CCCD:");

        CCCDHKText.setEditable(false);
        CCCDHKText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CCCDHKTextActionPerformed(evt);
            }
        });

        jLabel17.setText("Ngày sinh:");

        DateHKText.setEditable(false);
        DateHKText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateHKTextActionPerformed(evt);
            }
        });

        loaisoBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thường trú", "Tạm trú" }));

        jLabel10.setText("Diện tích");

        DienTich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DienTichActionPerformed(evt);
            }
        });

        jLabel25.setForeground(new java.awt.Color(255, 0, 51));
        jLabel25.setText("(*)");

        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("(*)");
        
        lblThngTinH = new JLabel();
        lblThngTinH.setText("Thông tin hộ khẩu");
        lblThngTinH.setForeground(new Color(0, 102, 153));
        lblThngTinH.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addComponent(jLabel15, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(nameHKText, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel2Layout.createSequentialGroup()
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel13)
        								.addComponent(jLabel14))
        							.addPreferredGap(ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
        							.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(SoNhaHKText, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE)
        								.addComponent(loaisoBox, GroupLayout.PREFERRED_SIZE, 210, GroupLayout.PREFERRED_SIZE))
        							.addGap(2)))
        					.addGap(2)
        					.addComponent(jLabel25)
        					.addGap(18)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING, false)
        							.addComponent(jLabel17, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE)
        							.addComponent(jLabel16, GroupLayout.PREFERRED_SIZE, 76, GroupLayout.PREFERRED_SIZE))
        						.addComponent(jLabel10, GroupLayout.PREFERRED_SIZE, 69, GroupLayout.PREFERRED_SIZE))
        					.addGap(56)
        					.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(DateHKText, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        						.addComponent(CCCDHKText, GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        						.addComponent(DienTich))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabel26)
        					.addGap(54))
        				.addGroup(jPanel2Layout.createSequentialGroup()
        					.addComponent(lblThngTinH, GroupLayout.PREFERRED_SIZE, 137, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(585, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(7)
        			.addComponent(lblThngTinH, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(jLabel15)
        				.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(nameHKText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel16)
        					.addComponent(CCCDHKText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel13)
        				.addComponent(jLabel17)
        				.addComponent(DateHKText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel25)
        				.addComponent(SoNhaHKText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel14)
        				.addComponent(jLabel10)
        				.addComponent(DienTich, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel26)
        				.addComponent(loaisoBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jPanel4.setBackground(new Color(230, 242, 255));

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addContainerGap(467, Short.MAX_VALUE)
        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addGap(18)
        			.addComponent(jButton4)
        			.addGap(18)
        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel4Layout.createSequentialGroup()
        			.addGroup(jPanel4Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton4)
        				.addComponent(jButton2))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4.setLayout(jPanel4Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
        				.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 734, Short.MAX_VALUE)
        				.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 283, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 160, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jPanel4, GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date namSinh;
    try{
        String ngaySinh = dateFormat.format(this.ngaySinhText.getDate());
        namSinh = dateFormat.parse(ngaySinh);
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Sai định dạng ngày sinh");  
        return;
    }
    
    
    if(this.cccdText.getText().equals("") || this.nameText.getText().equals("") 
            || this.regionText.getText().equals("")
            || this.countryText.getText().equals("")
            || this.workText.getText().equals("")
            || this.jobText.getText().equals("")
            || this.queText.getText().equals("")
            || this.DienTich.getText().equals("")
            || this.SoNhaHKText.getText().equals(""))  {
        JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin !");  
        return;
    }
       
    String CCCD = this.cccdText.getText();
    String hoTen = this.nameText.getText();
    
    String gioiTinh = this.sexBox.getSelectedItem()+"";
    String nguyenQuan = this.queText.getText();
    String danToc = this.regionText.getText();
    String quocTich = this.countryText.getText();
    String noiLamViec = this.workText.getText();
    String ngheNghiep = this.jobText.getText();
    String tinhTrang = this.loaisoBox.getSelectedItem()+"";
    if(tinhTrang.equals("Tạm trú")){
        tinhTrang = "Chưa khai báo";    
    }
    
    
    NhanKhauModel nk = new NhanKhauModel(CCCD,hoTen,namSinh,gioiTinh,nguyenQuan,danToc,quocTich,noiLamViec,"BlueMoon",ngheNghiep,tinhTrang);
    
    
    String IdChuHo = this.newHKControl.addNhanKhau(nk);
    int dienTich;
    if(IdChuHo !=null){
        String soNha = this.SoNhaHKText.getText();
        String loaiSo = this.loaisoBox.getSelectedItem()+"";
        String tenChuHo = this.nameHKText.getText();
        try{
            dienTich = Integer.parseInt(this.DienTich.getText());
        }catch(Exception e){
            dienTich = 0;
        }
        
        HoKhauModel hk = new HoKhauModel(soNha,nk.getCCCD(),loaiSo,tenChuHo, dienTich);
        
            String quanHeChuHo = "chủ hộ";
            String nameTV = hoTen;
            
        if(this.newHKControl.addHoKhau(hk)){
            JOptionPane.showMessageDialog(this, "Đăng ký hộ khẩu" +"thành công");
            ThanhVienModel tv = new ThanhVienModel(CCCD,soNha,quanHeChuHo,nameTV);
            this.newHKControl.themThanhVien(tv);
        }else{
            this.newHKControl.xoaNhanKhau(CCCD);
            JOptionPane.showMessageDialog(this, "Hộ khẩu sai hoặc đã tồn tại \nVui lòng sửa lại!");     
        }  

    }
    else{
        JOptionPane.showMessageDialog(this, "Chủ hộ sai hoặc đã tồn tại \nVui lòng sửa lại!");      
    } 

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HoKhauView viewMain = new HoKhauView();
        this.setVisible(false);
        viewMain.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.xoaForm();
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void CCCDHKTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CCCDHKTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CCCDHKTextActionPerformed

    private void DateHKTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateHKTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateHKTextActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.nameHKText.setText(this.nameText.getText());
        this.CCCDHKText.setText(this.cccdText.getText());
        this.DateHKText.setText(this.ngaySinhText.getDate()+"");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void queTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_queTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_queTextActionPerformed

    private void jobTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jobTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jobTextActionPerformed

    private void workTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workTextActionPerformed

    private void countryTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextActionPerformed

    private void regionTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regionTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regionTextActionPerformed

    private void cccdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cccdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cccdTextActionPerformed

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameTextActionPerformed

    private void DienTichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DienTichActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DienTichActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CCCDHKText;
    private javax.swing.JTextField DateHKText;
    private javax.swing.JTextField DienTich;
    private javax.swing.JTextField SoNhaHKText;
    private javax.swing.JTextField cccdText;
    private javax.swing.JTextField countryText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jobText;
    private javax.swing.JComboBox<String> loaisoBox;
    private javax.swing.JTextField nameHKText;
    private javax.swing.JTextField nameText;
    private com.toedter.calendar.JDateChooser ngaySinhText;
    private javax.swing.JTextField queText;
    private javax.swing.JTextField regionText;
    private javax.swing.JComboBox<String> sexBox;
    private javax.swing.JTextField workText;
    private JLabel lblThngTinH;
    private JLabel lblThngTinCh;
    // End of variables declaration//GEN-END:variables
}
