/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GuiXeView;
import view.GuiXeView;
import GuiXeController.DangKiGuiXe;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.PhuongTien;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import DongTienView.DongTienHK;
import javax.swing.JLabel;
/**
 *
 * @author MY PC
 */
public class DangKiGuiXeView extends javax.swing.JFrame {

    /**
     * Creates new form DangKiGuiXeView
     */
    DangKiGuiXe dangKiGXControl;
    String option = new String();
    
    public DangKiGuiXeView(String option) {
    	setTitle("Form đăng ký gửi xe");
    	setIconImage(Toolkit.getDefaultToolkit().getImage(DangKiGuiXeView.class.getResource("/img/apartment_13889041-min.png")));
    	getContentPane().setBackground(new Color(230, 242, 255));
        initComponents();
         this.option = option;
        dangKiGXControl = new DangKiGuiXe(this);
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(0, 102, 153));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6.setForeground(new Color(0, 102, 153));
        sonhaText = new javax.swing.JTextField();
        biensoText = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        LoaiXeBox = new javax.swing.JComboBox<>();
        chuxeText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));
        jPanel1.setBorder(null); // NOI18N

        jLabel1.setText("Số nhà");

        jLabel2.setText("Tên chủ xe");

        jLabel3.setText("Biển số xe");

        jLabel6.setText("Loại xe");

        sonhaText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sonhaTextActionPerformed(evt);
            }
        });

        biensoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biensoTextActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        LoaiXeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Xe máy", "Ô tô" }));

        chuxeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chuxeTextActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("(*)");

        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("(*)");

        jLabel7.setForeground(new java.awt.Color(255, 0, 51));
        jLabel7.setText("(*)");

        jLabel8.setForeground(new java.awt.Color(255, 0, 51));
        jLabel8.setText("(*)");
        
        lblThngTinPhng = new JLabel();
        lblThngTinPhng.setText("Thông tin phương tiện");
        lblThngTinPhng.setForeground(new Color(0, 102, 153));
        lblThngTinPhng.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addContainerGap(25, Short.MAX_VALUE)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        								.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        							.addGap(83)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        								.addComponent(sonhaText)
        								.addComponent(biensoText)
        								.addComponent(LoaiXeBox, 0, 267, Short.MAX_VALUE)
        								.addComponent(chuxeText, Alignment.TRAILING))
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel4)
        								.addComponent(jLabel5)
        								.addComponent(jLabel7)
        								.addComponent(jLabel8))
        							.addGap(18))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addGap(18)
        							.addComponent(jButton4)
        							.addPreferredGap(ComponentPlacement.UNRELATED)
        							.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED))))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(157)
        					.addComponent(lblThngTinPhng, GroupLayout.PREFERRED_SIZE, 190, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(5)
        			.addComponent(lblThngTinPhng, GroupLayout.PREFERRED_SIZE, 21, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(sonhaText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel4))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(chuxeText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(biensoText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel6)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(LoaiXeBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addComponent(jLabel8)))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton4)
        				.addComponent(jButton2))
        			.addGap(56))
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 225, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(10, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sonhaTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sonhaTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sonhaTextActionPerformed

    private void biensoTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biensoTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biensoTextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PhuongTien pt = new PhuongTien();
        
        String soNha = new String();
        String tenchu = new String();
        String bienso = new String();
        String loaixe = new String();

        if(this.sonhaText.getText().equals("")|| this.chuxeText.getText().equals("")|| this.biensoText.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin !");
        }else{
            try{    
                soNha = this.sonhaText.getText();
                tenchu = this.chuxeText.getText();
                bienso = this.biensoText.getText();
                loaixe = this.LoaiXeBox.getSelectedItem()+"";
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, "Vui lòng điền đúng định dạng !");
                return;
            }

            pt.setSoNha(soNha);
            pt.setBienSo(bienso);
            pt.setLoaiXe(loaixe);
            pt.setTenChuXe(tenchu);


            if(option.equals("add")){
                if(dangKiGXControl.kiemTraThanhVien(soNha, tenchu))
                    dangKiGXControl.addPhuongTien(pt);
                else{
                    JOptionPane.showMessageDialog(this, "Sai thông tin !");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GuiXeView viewMain = new GuiXeView();
        this.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //xoaForm();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void chuxeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chuxeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chuxeTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> LoaiXeBox;
    private javax.swing.JTextField biensoText;
    private javax.swing.JTextField chuxeText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField sonhaText;
    private JLabel lblThngTinPhng;
    // End of variables declaration//GEN-END:variables
}
