/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KhoanThuView;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import view.KhoanThuView;
import KhoanThuController.ThemKhoanThuController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import model.KhoanThu;
import service.ExcelReader;
import javax.swing.JLabel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Color;
import javax.swing.JSeparator;

/**
 *
 * @author MY PC
 */
public class ThemKhoanThu extends javax.swing.JFrame {

    /**
     * Creates new form ThemKhoanThu
     */
    
    String option = new String();
    private ThemKhoanThuController addKT;
    ExcelReader serice;
    
    public ThemKhoanThu() {
    	setTitle("Thêm khoản thu");
    	setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(ThemKhoanThu.class.getResource("/img/apartment_13889041-min.png")));
        initComponents();
        addKT  = new ThemKhoanThuController(this);
         this.setLocationRelativeTo(null);
         serice = new ExcelReader();
         this.LoaiKhoanThu.setEnabled(true);
         this.DichVu.setEnabled(true);
         
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
         
         
        this.setVisible(true);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDayChooser1 = new com.toedter.calendar.JDayChooser();
        jYearChooser1 = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setForeground(new Color(0, 102, 153));
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel1.setForeground(new Color(0, 102, 153));
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel2.setForeground(new Color(0, 102, 153));
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel3.setForeground(new Color(0, 102, 153));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel6.setForeground(new Color(0, 102, 153));
        TenKhoanThu = new javax.swing.JTextField();
        TrangThai = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton1.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setBorderPainted(false);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorderPainted(false);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel12.setForeground(new Color(0, 102, 153));
        idText = new javax.swing.JTextField();
        LoaiKhoanThu = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel7.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel7.setForeground(new Color(0, 102, 153));
        DonGia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel8.setForeground(new Color(0, 102, 153));
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel9.setForeground(new Color(0, 102, 153));
        CongTy = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel10.setForeground(new Color(0, 102, 153));
        DichVu = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel11.setForeground(new Color(0, 102, 153));
        XeMay = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel13.setForeground(new Color(0, 102, 153));
        Oto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel14.setFont(new Font("Tahoma", Font.PLAIN, 13));
        jLabel14.setForeground(new Color(0, 102, 153));
        jButton6 = new javax.swing.JButton();
        jButton6.setBorderPainted(false);
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        ngayBDText = new com.toedter.calendar.JDateChooser();
        ngayBDText.getCalendarButton().setBackground(Color.white);
        
        

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(230, 242, 255));
        jPanel1.setBorder(null); // NOI18N

        jLabel1.setText("Tên khoản thu");

        jLabel2.setText("Loại khoản thu");

        jLabel3.setText("Ngày bắt đầu:");

        jLabel6.setText("Trạng thái");

        TenKhoanThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TenKhoanThuActionPerformed(evt);
            }
        });

        TrangThai.setEditable(false);
        TrangThai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrangThaiActionPerformed(evt);
            }
        });

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Clear all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("ID: ");

        LoaiKhoanThu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Phí dịch vụ", "Phí quản lý", "Phí đóng góp", "Phí gửi xe", "Phí thu hộ" }));
        LoaiKhoanThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoaiKhoanThuActionPerformed(evt);
            }
        });

        jLabel7.setText("Đơn giá:");

        DonGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DonGiaActionPerformed(evt);
            }
        });

        jLabel8.setText("( đơn vị: nghìn Đồng/m2 )");

        jLabel9.setText("Tên công ty  cấp");

        CongTy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CongTyActionPerformed(evt);
            }
        });

        jLabel10.setText("Tên dịch vụ:");

        DichVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Điện", "Nước", "Internet" }));

        jLabel11.setText("Giá xe máy: ");

        XeMay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XeMayActionPerformed(evt);
            }
        });

        jLabel13.setText("Giá ô tô: ");

        Oto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtoActionPerformed(evt);
            }
        });

        jLabel14.setText("( đơn vị: nghìn Đồng/xe)");

        jButton6.setText("Next");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel27.setForeground(new java.awt.Color(255, 0, 51));
        jLabel27.setText("(*)");

        jLabel28.setForeground(new java.awt.Color(255, 0, 51));
        jLabel28.setText("(*)");

        jLabel29.setForeground(new java.awt.Color(255, 0, 51));
        jLabel29.setText("(*)");

        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("(*)");

        ngayBDText.setDateFormatString("yyyy-MM-dd");
        
        JLabel lblThngTinKhon = new JLabel();
        lblThngTinKhon.setForeground(new Color(0, 102, 153));
        lblThngTinKhon.setFont(new Font("Segoe UI Variable", Font.BOLD, 16));
        lblThngTinKhon.setText("Thông tin khoản thu");
        
        JSeparator separator = new JSeparator();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(404, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 159, GroupLayout.PREFERRED_SIZE)
        					.addGap(216))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton4)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(lblThngTinKhon, GroupLayout.PREFERRED_SIZE, 185, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(584, Short.MAX_VALUE))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(25)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel6, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel9, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel10, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jLabel11, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(jLabel13, GroupLayout.PREFERRED_SIZE, 87, GroupLayout.PREFERRED_SIZE))
        					.addGap(83))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        					.addPreferredGap(ComponentPlacement.RELATED)))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(TenKhoanThu, GroupLayout.PREFERRED_SIZE, 267, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED, 96, Short.MAX_VALUE)
        					.addComponent(idText, GroupLayout.PREFERRED_SIZE, 166, GroupLayout.PREFERRED_SIZE)
        					.addGap(47))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(TrangThai)
        							.addComponent(LoaiKhoanThu, 0, 267, Short.MAX_VALUE)
        							.addComponent(CongTy)
        							.addComponent(DichVu, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(XeMay, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
        							.addComponent(ngayBDText, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        						.addComponent(DonGia, 267, 267, 267))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addComponent(jLabel28)
        								.addComponent(jLabel29))
        							.addGap(31)
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel12, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
        									.addGap(182)
        									.addComponent(jLabel30, GroupLayout.PREFERRED_SIZE, 25, GroupLayout.PREFERRED_SIZE))
        								.addComponent(jLabel8, GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)))
        						.addComponent(jLabel27)
        						.addComponent(jButton6, GroupLayout.PREFERRED_SIZE, 75, GroupLayout.PREFERRED_SIZE))
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(Oto, GroupLayout.PREFERRED_SIZE, 184, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap(392, Short.MAX_VALUE))))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(39)
        			.addComponent(separator, GroupLayout.PREFERRED_SIZE, 1, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(739, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(7)
        			.addComponent(lblThngTinKhon)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel1)
        				.addComponent(TenKhoanThu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel12)
        				.addComponent(idText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel29)
        				.addComponent(jLabel30))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel2)
        				.addComponent(LoaiKhoanThu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel28))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        					.addComponent(jLabel3)
        					.addComponent(jLabel27))
        				.addComponent(ngayBDText, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel6)
        				.addComponent(TrangThai, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jButton6))
        			.addPreferredGap(ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
        			.addComponent(separator, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel8)
        				.addComponent(DonGia, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7))
        			.addGap(18)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel9)
        					.addGap(29)
        					.addComponent(jLabel10)
        					.addGap(18)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabel11)
        						.addComponent(XeMay, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(21)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabel13)
        						.addComponent(Oto, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(CongTy, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(18)
        					.addComponent(DichVu, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addGap(40)
        					.addComponent(jLabel14, GroupLayout.PREFERRED_SIZE, 16, GroupLayout.PREFERRED_SIZE)))
        			.addGap(8)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2)
        				.addComponent(jButton4))
        			.addContainerGap())
        );
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.TRAILING)
        		.addComponent(jPanel1, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 779, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addComponent(jPanel1, GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        KhoanThuView viewMain = new KhoanThuView();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
    Date ngayBatDau;
    try{
        String ngay = dateFormat.format(this.ngayBDText.getDate());
        ngayBatDau = dateFormat.parse(ngay);
    }catch(Exception e){
        JOptionPane.showMessageDialog(this, "Sai định dạng ngày");  
        return;
    }
        
        if(this.TenKhoanThu.getText().equals("") || this.idText.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí !");
              return; 
         }else{
             if( (this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ") || this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")) && this.DonGia.getText().equals("")){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin khoản thu !");
                 return; 
             }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe") && (this.Oto.getText().equals("") ||this.XeMay.getText().equals(""))){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí gửi xe!");
                 return; 
             }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ") && (this.CongTy.getText().equals(""))){
                 JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ thông tin phí thu hộ!");
                 return; 
             }
                        
         }
        
        
        String id = this.idText.getText();
        String tenKhoanThu = this.TenKhoanThu.getText();
        String loaiKhoanThu = this.LoaiKhoanThu.getSelectedItem()+"";
        

    
    String trangThai = "Chưa hoàn thành";
    
    
    KhoanThu khoanthu = new KhoanThu();
    
    khoanthu.setIdKhoanThu(id);
    khoanthu.setTenKhoanThu(tenKhoanThu);
    khoanthu.setLoaiKhoanThu(loaiKhoanThu);
    khoanthu.setNgayBatDau(ngayBatDau);
    khoanthu.setTrangThai(trangThai);
    
    
        if(this.addKT.addKhoanThu(khoanthu)){
        
        if(this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ")){
            int donGia = Integer.parseInt(this.DonGia.getText());
            khoanthu.setDonGia(donGia);
            this.addKT.addPhiBatBuoc(khoanthu);
            
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")){
            int donGia = Integer.parseInt(this.DonGia.getText());
            khoanthu.setDonGia(donGia);
            this.addKT.addPhiBatBuoc(khoanthu);
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí đóng góp")){
            khoanthu.setTongThu(0);
            this.addKT.addPhiDongGop(khoanthu);
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe")){
            int giaXeMay = Integer.parseInt(this.XeMay.getText());
            int giaOto = Integer.parseInt(this.Oto.getText());
            khoanthu.setXemay(giaXeMay);
            khoanthu.setOto(giaOto);
            this.addKT.addPhiGuiXe(khoanthu);
            
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ")){
            String tenCongTy = this.CongTy.getText();
            String dichVu = this.DichVu.getSelectedItem()+"";
            khoanthu.setTenCongTy(tenCongTy);
            khoanthu.setDichVu(dichVu);
            this.addKT.addPhiThuHo(khoanthu);
        }
        this.addKT.themDanhSachHoDong(khoanthu);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TrangThaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrangThaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TrangThaiActionPerformed

    private void TenKhoanThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TenKhoanThuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TenKhoanThuActionPerformed

    private void DonGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DonGiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DonGiaActionPerformed

    private void CongTyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CongTyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CongTyActionPerformed

    private void XeMayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XeMayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_XeMayActionPerformed

    private void OtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OtoActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if(this.LoaiKhoanThu.getSelectedItem().equals("Phí dịch vụ") || this.LoaiKhoanThu.getSelectedItem().equals("Phí quản lý")){
         this.DonGia.setVisible(true);
         this.jLabel7.setVisible(true);
         this.jLabel8.setVisible(true);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
         
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí gửi xe")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(true);
         this.jLabel11.setVisible(true);
         this.XeMay.setVisible(true);
         this.jLabel13.setVisible(true);
         this.jLabel14.setVisible(true);
        }if(this.LoaiKhoanThu.getSelectedItem().equals("Phí thu hộ")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(true);
         this.jLabel9.setVisible(true);
         this.DichVu.setVisible(true);
         this.jLabel10.setVisible(true);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
        }else if(this.LoaiKhoanThu.getSelectedItem().equals("Phí đóng góp")){
         this.DonGia.setVisible(false);
         this.jLabel7.setVisible(false);
         this.jLabel8.setVisible(false);
         this.CongTy.setVisible(false);
         this.jLabel9.setVisible(false);
         this.DichVu.setVisible(false);
         this.jLabel10.setVisible(false);
         this.Oto.setVisible(false);
         this.jLabel11.setVisible(false);
         this.XeMay.setVisible(false);
         this.jLabel13.setVisible(false);
         this.jLabel14.setVisible(false);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void LoaiKhoanThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoaiKhoanThuActionPerformed

    }//GEN-LAST:event_LoaiKhoanThuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CongTy;
    private javax.swing.JComboBox<String> DichVu;
    private javax.swing.JTextField DonGia;
    private javax.swing.JComboBox<String> LoaiKhoanThu;
    private javax.swing.JTextField Oto;
    private javax.swing.JTextField TenKhoanThu;
    private javax.swing.JTextField TrangThai;
    private javax.swing.JTextField XeMay;
    private javax.swing.JTextField idText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDayChooser jDayChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private com.toedter.calendar.JYearChooser jYearChooser1;
    private com.toedter.calendar.JDateChooser ngayBDText;
}
